name: Busha Commerce JS develop
on:
  push:
    branches:
      - develop
env:
  PAYMENT_UI: ${{ vars.PAYMENT_UI_STAGING }}
  CYPRESS_PUBLIC_KEY: ${{ vars.CYPRESS_PUBLIC_KEY_STAGING }}

jobs:
  run-unit-test-for-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm i
      - run: npm run test:ci

  run-e2e-test-for-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          command: npm run test:e2e:ci

  generate-output-for-staging:
    needs: [run-unit-test-for-staging, run-e2e-test-for-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm i
      - run: npm run build
      - run: git config user.email "abolajibisiriyu@gmail.com"
      - run: git config user.name "Abolaji Bisiriyu"
      - run: npm version patch -m "bumped to %s" -f
      - run: rm -rf output
      - run: cp -rf dist output
      - run: git add .
      - run: git commit -m "generated develop output"
      - run: git push
