name: Busha Cloud Functions Develop
on:
  push:
    branches:
      - develop
env:
  PAYMENT_UI: ${{ vars.PAYMENT_UI_STAGING }}
jobs:
  generate-output-for-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn
      - run: yarn build
      - run: rm -r output
      - run: cp -rf dist output
      - run: git config user.email "abolajibisiriyu@gmail.com"
      - run: git config user.name "Abolaji Bisiriyu"
      - run: git add .
      - run: git commit -m "generated staging output"
      - run: git push
